import Head from "next/head";
import useSWR from "swr";
import { useCallback, useRef, useState, useEffect } from "react";

// components
import Card from "../components/card.js";

const fetcher = (url: string) => fetch(url).then((res) => res.json());

export default function Home() {
  const [query, setQuery] = useState("mamma");
  const { data, error } = useSWR(`/api/search?query=${query}`, fetcher);
  const isLoading = !data && !error;
  const inputRef = useRef(null);

  const onChange = useCallback((e) => {
    const query = e.target.value;
    setQuery(query);
  }, []);

  console.log(data);

  return (
    <>
      <Head>
        <title>ISL semantic search</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Semantic search in Icelandic</h1>

        <input
          type="text"
          value={query}
          onChange={onChange}
          ref={inputRef}
          placeholder="Search for a word"
        />
        {isLoading ? (
          <div>Loading...</div>
        ) : error ? (
          <div>Error: {error.message}</div>
        ) : (
          <div className="cards">
            {data.map(({ text, _additional }, i: int) => (
              <Card title={text} certainty={_additional.certainty} key={i} />
            ))}
          </div>
        )}
      </main>
    </>
  );
}

// export default WordPage;
