import Head from "next/head";

async function search() {
  const response = await fetch("/api/search?query=fiskur");
  const jsonData = await response.json();
  console.log(jsonData);
}

export default function Home() {
  let data = search();
  console.log(data);

  return (
    <>
      <Head>
        <title>ISL semantic search</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Semantic search in Icelandic</h1>
      </main>
    </>
  );
}

// export default WordPage;
