import Head from "next/head";
import useSWR from "swr";
import { useCallback, useRef, useState, useEffect } from "react";
// components
import Card from "../components/card.js";

const fetcher = (url: string) => fetch(url).then((res) => res.json());

export default function Lexical() {
  const [query, setQuery] = useState("");
  const [noResult, setNoResult] = useState(false);
  const { data, error, isLoading } = useSWR(
    `/api/lexical?query=${query}`,
    fetcher
  );
  const [amountOfArticles, setAmountOfArticles] = useState(0);
  const inputRef = useRef(null);

  const onChange = useCallback((e) => {
    const query = e.target.value;
    setQuery(query);
    setNoResult(false);
  }, []);

  // Check if data is null or an empty array to determine if there are no results
  useEffect(() => {
    if (!isLoading && data && data.length === 0) {
      setNoResult(true);
    }
  }, [data, isLoading]);

  // console.log(data);

  return (
    <>
      <Head>
        <title>ISL semantic search</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <header>
          <h1>Kaboom | hröð merkingarfræðileg leit á Íslensku</h1>
          <p>(e. fast semantic search in Icelandic)</p>
        </header>

        <div className="result">
          <input
            type="text"
            value={query}
            onChange={onChange}
            ref={inputRef}
            placeholder="leitarmynd"
          />
          {noResult && <div className="info noresult">Engar niðurstöður</div>}
          {isLoading ? (
            <div className="info loading">Hleður...</div>
          ) : error ? (
            <div className="info error">Villa: {error.message}</div>
          ) : (
            <div className="cards">
              {data.map(({ text, summary }, i: int) => (
                <Card title={text} summary={summary} key={i} />
              ))}
            </div>
          )}
        </div>
      </main>
    </>
  );
}
